#
# Sets up network using flannel plugin.
#
---

- name: Download 'calico' network plugin yaml
  local_action: "shell wget -O /tmp/net.yaml '{{ CALICO_YAML_URL }}'"
  args:
    warn: no
- name: adapt 'calico' network plugin yaml
  local_action: shell sed -i 's/192.168.0.0/{{ POD_NETWORK_CIDR | regex_replace('/.*', '') }}/' /tmp/net.yaml
