#
# Sets up the blackbox exporter
#
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: blackbox-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackbox-exporter
  template:
    metadata:
      labels:
        app: blackbox-exporter
    spec:
      containers:
      - name: blackbox-exporter
        image: quay.io/prometheus/blackbox-exporter:v0.12.0
        ports:
        - name: metrics
          containerPort: 9115
---
apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter
  labels:
    app: blackbox-exporter
spec:
  ports:
  - name: http-metrics
    port: 9115
    protocol: TCP
    targetPort: metrics
  selector:
    app: blackbox-exporter
