#
# Upgrade a cluster's masters:
# - get and install kubeadm binary in the target version
# - for all masters (one by one):
#   * shut down keepalived
#   * upgrade cluster using kubeadm
#   * start keepalived
#
---

- name: Make sure some needed software is installed via package manager
  ansible.builtin.include_tasks:
    file: "{{ playbook_dir }}/tasks/install-or-upgrade-kubeadm.yaml"

- name: Upgrade masters one by one
  ansible.builtin.include_tasks: upgrade-master.yaml
  with_items: "{{ groups['masters'] }}"
  loop_control:
    loop_var: master

- name: Upgrade software
  ansible.builtin.include_tasks:
    file: "{{ playbook_dir }}/tasks/install-or-upgrade-k8n-packages.yaml"

- name: Restart kubelet
  ansible.builtin.systemd:
    name: kubelet
    daemon_reload: true
    state: restarted

- name: Set coredns replicas (just in case)
  ansible.builtin.shell: "export KUBECONFIG=/etc/kubernetes/admin.conf; kubectl scale --replicas={{ groups['masters'] | length }} -n kube-system deployment/coredns" # noqa yaml[line-length] no-changed-when
  when: "'primary_master' in group_names"
