#
# Install fetched images on the target host.
#
---
- name: Copy Kubernetes images
  ansible.builtin.copy:
    src: "/tmp/{{ (item.name + ':' + item.tag) | hash('sha256') }}.tar"
    dest: "/tmp/{{ (item.name + ':' + item.tag) | hash('sha256') }}.tar"
    mode: "0644"
  with_items: "{{ DOCKER_IMAGES }}"

- name: Copy network plugin images
  ansible.builtin.copy:
    src: "/tmp/{{ item | hash('sha256') }}.tar"
    dest: "/tmp/{{ item | hash('sha256') }}.tar"
    mode: "0644"
  with_items: "{{ NETWORK_PLUGIN_IMAGE_SPECS_RESULT.stdout_lines }}"

- name: Load Kubernetes images
  ansible.builtin.command: "/usr/bin/docker load -i /tmp/{{ (item.name + ':' + item.tag) | hash('sha256') }}.tar" # noqa no-changed-when
  with_items: "{{ DOCKER_IMAGES }}"

- name: Load network plugin images
  ansible.builtin.command: "/usr/bin/docker load -i /tmp/{{ item | hash('sha256') }}.tar" # noqa no-changed-when
  with_items: "{{ NETWORK_PLUGIN_IMAGE_SPECS_RESULT.stdout_lines }}"
