#
# Image versions for exporting and importing
#
---

# Versions.
# When upgrading to a new k8s version, you can use `kubeadm config images list' to print a list of images:tags

BUSYBOX_TAG: "1.37.0"
COREDNS_TAG: "v1.12.0"
DASHBOARD_TAG: "v2.7.0"
ETCD_TAG: "3.5.21-0"
HAPROXY_TAG: "3.2.3"
KEEPALIVED_TAG: "2.0.20"
KUBERNETES_TAG: "v1.33.3"
KUBE_VIP_TAG: "v1.0.0"
METRICS_SCRAPER_TAG: "v1.0.8"
METRICS_SERVER_TAG: "v0.3.6"
NGINX_TAG: "1.29.0"
PAUSE_TAG: "3.1"


# Images for prefetching
DOCKER_IMAGES: [
  { name: "busybox", tag: "{{ BUSYBOX_TAG }}" },
  { name: "registry.k8s.io/coredns/coredns", tag: "{{ COREDNS_TAG }}" },
  { name: "registry.k8s.io/etcd", tag: "{{ ETCD_TAG }}" },
  { name: "registry.k8s.io/metrics-server-{{ HOST_ARCH }}", tag: "{{ METRICS_SERVER_TAG }}" },
  { name: "registry.k8s.io/kube-apiserver-{{ HOST_ARCH }}", tag: "{{ KUBERNETES_TAG }}" },
  { name: "registry.k8s.io/kube-controller-manager-{{ HOST_ARCH }}", tag: "{{ KUBERNETES_TAG }}" },
  { name: "registry.k8s.io/kube-proxy-{{ HOST_ARCH }}", tag: "{{ KUBERNETES_TAG }}" },
  { name: "registry.k8s.io/kube-scheduler-{{ HOST_ARCH }}", tag: "{{ KUBERNETES_TAG }}" },
  { name: "registry.k8s.io/pause", tag: "{{ PAUSE_TAG }}" },
  { name: "osixia/keepalived", tag: "{{ KEEPALIVED_TAG }}" },
  { name: "nginx", tag: "{{ NGINX_TAG }}" },
  { name: "haproxy", tag: "{{ HAPROXY_TAG }}" },
  { name: "kubernetesui/metrics-scraper-{{ HOST_ARCH }}", tag: "{{ METRICS_SCRAPER_TAG }}" },
  { name: "kubernetesui/dashboard-{{ HOST_ARCH }}", tag: "{{ DASHBOARD_TAG }}" },
  { name: "plndr/kube-vip", tag: "{{ KUBE_VIP_TAG }}" },
]
