#
# Set up Fluentd to collect logs for Elasticsearch
#
---
- name: Create directory for Fluentd installation
  ansible.builtin.file: "path=/root/setup/fluentd mode=0755 state=directory"

- name: Copy Fluentd yaml files
  ansible.builtin.copy: "src={{ item }} dest=/root/setup/fluentd/ mode=0644"
  with_items:
  - fluentd-es-configmap.yaml
  - fluentd-es-ds.yaml
  - fluentd-es-serviceaccount.yaml

- name: Install Fluentd
  ansible.builtin.shell: "export KUBECONFIG=/etc/kubernetes/admin.conf; kubectl create -f /root/setup/fluentd/" # noqa no-changed-when
