#
# Playbook to upgrade a Kubernetes cluster.
#
---

- name: Upgrade the master nodes
  hosts: masters
  remote_user: root
  gather_facts: true
  any_errors_fatal: true
  roles:
    - upgrade_masters
  tags:
    - upgrade-masters

- name: Upgrade the minions
  hosts: nodes
  remote_user: root
  gather_facts: true
  any_errors_fatal: true
  roles:
    - upgrade_minions
  tags:
    - upgrade-minions
