#
# Playbook to connect a cluster to the local machine (for remote kubectl access)
#
---

- name: Get settings file
  hosts: primary_master
  remote_user: root
  gather_facts: false
  any_errors_fatal: true
  roles:
    - local_access
  tags:
    - local-access
