#
# Playbook to uninstall the EFK stack
#
---

- name: Uninstall Kibana
  hosts: primary_master
  remote_user: root
  gather_facts: no
  any_errors_fatal: yes
  tasks:
  - name: Uninstalling Kibana...
    ansible.builtin.import_tasks: roles/kibana/tasks/uninstall.yaml
  tags:
  - uninstall-kibana

- name: Uninstall Elasticsearch
  hosts: primary_master
  remote_user: root
  gather_facts: no
  any_errors_fatal: yes
  tasks:
  - name: Uninstalling Elasticsearch...
    ansible.builtin.import_tasks: roles/elasticsearch/tasks/uninstall.yaml
  tags:
  - uninstall-elasticsearch

- name: Uninstall Fluentd
  hosts: primary_master
  remote_user: root
  gather_facts: no
  any_errors_fatal: yes
  tasks:
  - name: Uninstalling Fluentd...
    ansible.builtin.import_tasks: roles/fluentd/tasks/uninstall.yaml
  tags:
  - uninstall-fluentd

- name: Clean up Elasticsearch and fluentd data
  hosts: nodes
  remote_user: root
  gather_facts: no
  any_errors_fatal: yes
  tasks:
  - name: Cleanup files created by EFK stack software
    ansible.builtin.shell: "rm -rf /var/log/fluentd-buffers /var/lib/es/*" # noqa no-changed-when deprecated-command-syntax
  tags:
  - cleanup-data
