#
# Playbook to set up prometheus operator.
#
--- 

- name: Set up prometheus operator
  hosts: masters
  remote_user: root
  gather_facts: no
  any_errors_fatal: yes
  roles:
  - {role: prometheus_operator,      when: "'primary_master'    in group_names" }
  tags:
  - prometheus_operator

