#
# Playbook to set up EFK stack for logging.
#
--- 
- name: Label Elasticsearch nodes
  hosts: nodes
  remote_user: root
  gather_facts: yes
  any_errors_fatal: yes
  tasks:
  - name: Labelling...
    ansible.builtin.import_tasks: "{{ playbook_dir }}/roles/elasticsearch/tasks/label.yaml"
    when: "'primary_master' in group_names"
  tags:
  - label

- name: Set up Elasticsearch
  hosts: primary_master
  remote_user: root
  gather_facts: no
  any_errors_fatal: yes
  roles:
  - elasticsearch
  tags:
  - elasticsearch

- name: Set up Kibana
  hosts: primary_master
  remote_user: root
  gather_facts: no
  any_errors_fatal: yes
  roles:
  - kibana
  tags:
  - kibana

- name: Set up Fluentd
  hosts: primary_master
  remote_user: root
  gather_facts: no
  any_errors_fatal: yes
  roles:
  - fluentd
  tags:
  - fluentd

