#
# Upgrade a cluster's nodes one by one:
# - cordon it if master, drain it if minion
# - shut down kubernetes services
# - upgrade its software
# - restart kubelet service
# - uncordon it
#
---

- name: Make sure some needed software is installed via package manager
  ansible.builtin.include_tasks:
    file: "{{ playbook_dir }}/tasks/install-or-upgrade-kubeadm.yaml"

- name: Perform upgrade sequence on all minions one by one
  ansible.builtin.include_tasks: upgrade-minion.yaml
  with_items: "{{ groups['minions'] }}"
  loop_control:
    loop_var: minion
