#
# Prepare node (i.e. set up and fix some files)
#
---

- name: Make sure some needed software is installed via package manager
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - perl

- name: Install kubeadm
  ansible.builtin.include_tasks:
    file: "{{ playbook_dir }}/tasks/install-or-upgrade-kubeadm.yaml"

- name: Install OS-native Kubernetes software
  ansible.builtin.include_tasks:
    file: "{{ playbook_dir }}/tasks/install-or-upgrade-k8n-packages.yaml"

- name: Enable kubelet
  ansible.builtin.service:
    name: kubelet
    enabled: true

- name: Create setup directory
  ansible.builtin.file:
    path: /root/setup
    state: directory
    mode: "0755"
  when: "'primary_master' in group_names"
