#
# Set up Kibana as frontend for Elasticsearch
#
---
- name: Create directory for Kibana installation
  ansible.builtin.file: "path=/root/setup/kibana mode=0755 state=directory"

- name: Copy Kibana yaml files
  ansible.builtin.copy: "src={{ item }} dest=/root/setup/kibana/ mode=0644"
  with_items:
  - kibana-deployment.yaml
  - kibana-service.yaml

- name: Install Kibana
  ansible.builtin.shell: "export KUBECONFIG=/etc/kubernetes/admin.conf; kubectl create -f /root/setup/kibana/" # noqa no-changed-when
